apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomizer-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: randomizer
  template:
    metadata:
      labels:
        app: randomizer
    spec:
      containers:
      - name: randomizer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-db:5432/llm_benchmark"
