apiVersion: v1
kind: Service
metadata:
  name: api-service
data:
  api-key: $(echo -n "secret_api_key" | base64)
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: api
